-- Generated automatically by bulk export script
-- Source: gsm8k cache

INSERT INTO seed_problems (
  source, external_id, grade, question_text, answer_text, correct_answers, topic, primary_unit, extracted_variables, number_range_id, operation_category_id, unknown_position_id, linguistic_complexity_id, cognitive_demand_id, operation_count_id, ai_full_return
)
VALUES
  ('gsm8k', '0', NULL, 'Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?', 'Natalia sold 48/2 = <<48/2=24>>24 clips in May.
Natalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.
#### 72', '{"value":72}', 'other', 'clips', '[{"name":"April sales","value":48},{"name":"May multiplier","value":0.5}]', 1, 3, 1, 2, 3, 2, '{"steps":[{"expr":"48/2","result":24},{"expr":"48+24","result":72}],"topic":"other","answer":"Natalia sold 48/2 = <<48/2=24>>24 clips in May.\nNatalia sold 48+24 = <<48+24=72>>72 clips altogether in April and May.\n#### 72","question":"Natalia sold clips to 48 of her friends in April, and then she sold half as many clips in May. How many clips did Natalia sell altogether in April and May?","final_result":72,"number_range":"1-100","primary_unit":"clips","number_of_steps":2,"operations_used":["division","addition"],"cognitive_demand":"plan","unknown_position":"result_unknown","extracted_variables":[{"name":"April sales","value":48},{"name":"May multiplier","value":0.5}],"language_complexity":"relationship"}'),
  ('gsm8k', '1', NULL, 'Weng earns $12 an hour for babysitting. Yesterday, she just did 50 minutes of babysitting. How much did she earn?', 'Weng earns 12/60 = $<<12/60=0.2>>0.2 per minute.
Working 50 minutes, she earned 0.2 x 50 = $<<0.2*50=10>>10.
#### 10', '{"value":10}', 'money', 'dollar', '[{"name":"hourly rate","value":12},{"name":"minutes babysat","value":50}]', 1, 2, 1, 2, 3, 2, '{"steps":[{"expr":"12/60","result":0.2},{"expr":"0.2*50","result":10}],"topic":"money","answer":"Weng earns 12/60 = $<<12/60=0.2>>0.2 per minute.\nWorking 50 minutes, she earned 0.2 x 50 = $<<0.2*50=10>>10.\n#### 10","question":"Weng earns $12 an hour for babysitting. Yesterday, she just did 50 minutes of babysitting. How much did she earn?","final_result":10,"number_range":"1-100","primary_unit":"dollar","number_of_steps":2,"operations_used":["division","multiplication"],"cognitive_demand":"plan","unknown_position":"result_unknown","extracted_variables":[{"name":"hourly rate","value":12},{"name":"minutes babysat","value":50}],"language_complexity":"relationship"}'),
  ('gsm8k', '2', NULL, 'Betty is saving money for a new wallet which costs $100. Betty has only half of the money she needs. Her parents decided to give her $15 for that purpose, and her grandparents twice as much as her parents. How much more money does Betty need to buy the wallet?', 'In the beginning, Betty has only 100 / 2 = $<<100/2=50>>50.
Betty''s grandparents gave her 15 * 2 = $<<15*2=30>>30.
This means, Betty needs 100 - 50 - 30 - 15 = $<<100-50-30-15=5>>5 more.
#### 5', '{"value":5}', 'money', 'dollar', '[{"name":"wallet cost","value":100},{"name":"current amount proportion","value":0.5},{"name":"parents contribution","value":15},{"name":"grandparents multiplier","value":2}]', 1, 3, 2, 2, 3, 5, '{"steps":[{"expr":"100/2","result":50},{"expr":"15*2","result":30},{"expr":"100-50-30-15","result":5}],"topic":"money","answer":"In the beginning, Betty has only 100 / 2 = $<<100/2=50>>50.\nBetty''s grandparents gave her 15 * 2 = $<<15*2=30>>30.\nThis means, Betty needs 100 - 50 - 30 - 15 = $<<100-50-30-15=5>>5 more.\n#### 5","question":"Betty is saving money for a new wallet which costs $100. Betty has only half of the money she needs. Her parents decided to give her $15 for that purpose, and her grandparents twice as much as her parents. How much more money does Betty need to buy the wallet?","final_result":5,"number_range":"1-100","primary_unit":"dollar","number_of_steps":5,"operations_used":["division","multiplication","subtraction"],"cognitive_demand":"plan","unknown_position":"change_unknown","extracted_variables":[{"name":"wallet cost","value":100},{"name":"current amount proportion","value":0.5},{"name":"parents contribution","value":15},{"name":"grandparents multiplier","value":2}],"language_complexity":"relationship"}'),
  ('gsm8k', '3', NULL, 'Julie is reading a 120-page book. Yesterday, she was able to read 12 pages and today, she read twice as many pages as yesterday. If she wants to read half of the remaining pages tomorrow, how many pages should she read?', 'Maila read 12 x 2 = <<12*2=24>>24 pages today.
So she was able to read a total of 12 + 24 = <<12+24=36>>36 pages since yesterday.
There are 120 - 36 = <<120-36=84>>84 pages left to be read.
Since she wants to read half of the remaining pages tomorrow, then she should read 84/2 = <<84/2=42>>42 pages.
#### 42', '{"value":42}', 'other', 'pages', '[{"name":"total pages","value":120},{"name":"yesterday pages","value":12},{"name":"today multiplier","value":2},{"name":"tomorrow fraction","value":0.5}]', 2, 3, 1, 2, 3, 4, '{"steps":[{"expr":"12*2","result":24},{"expr":"12+24","result":36},{"expr":"120-36","result":84},{"expr":"84/2","result":42}],"topic":"other","answer":"Maila read 12 x 2 = <<12*2=24>>24 pages today.\nSo she was able to read a total of 12 + 24 = <<12+24=36>>36 pages since yesterday.\nThere are 120 - 36 = <<120-36=84>>84 pages left to be read.\nSince she wants to read half of the remaining pages tomorrow, then she should read 84/2 = <<84/2=42>>42 pages.\n#### 42","question":"Julie is reading a 120-page book. Yesterday, she was able to read 12 pages and today, she read twice as many pages as yesterday. If she wants to read half of the remaining pages tomorrow, how many pages should she read?","final_result":42,"number_range":"100-500","primary_unit":"pages","number_of_steps":4,"operations_used":["multiplication","addition","subtraction","division"],"cognitive_demand":"plan","unknown_position":"result_unknown","extracted_variables":[{"name":"total pages","value":120},{"name":"yesterday pages","value":12},{"name":"today multiplier","value":2},{"name":"tomorrow fraction","value":0.5}],"language_complexity":"relationship"}'),
  ('gsm8k', '4', NULL, 'James writes a 3-page letter to 2 different friends twice a week.  How many pages does he write a year?', 'He writes each friend 3*2=<<3*2=6>>6 pages a week
So he writes 6*2=<<6*2=12>>12 pages every week
That means he writes 12*52=<<12*52=624>>624 pages a year
#### 624', '{"value":624}', 'other', 'pages', '[{"name":"pages per letter","value":3},{"name":"number of friends","value":2},{"name":"weekly repetitions","value":2}]', 3, 2, 1, 2, 2, 3, '{"steps":[{"expr":"3*2","result":6},{"expr":"6*2","result":12},{"expr":"12*52","result":624}],"topic":"other","answer":"He writes each friend 3*2=<<3*2=6>>6 pages a week\nSo he writes 6*2=<<6*2=12>>12 pages every week\nThat means he writes 12*52=<<12*52=624>>624 pages a year\n#### 624","question":"James writes a 3-page letter to 2 different friends twice a week.  How many pages does he write a year?","final_result":624,"number_range":"500-1000","primary_unit":"pages","number_of_steps":3,"operations_used":["multiplication"],"cognitive_demand":"choose","unknown_position":"result_unknown","extracted_variables":[{"name":"pages per letter","value":3},{"name":"number of friends","value":2},{"name":"weekly repetitions","value":2}],"language_complexity":"relationship"}'),
  ('gsm8k', '5', NULL, 'Mark has a garden with flowers. He planted plants of three different colors in it. Ten of them are yellow, and there are 80% more of those in purple. There are only 25% as many green flowers as there are yellow and purple flowers. How many flowers does Mark have in his garden?', 'There are 80/100 * 10 = <<80/100*10=8>>8 more purple flowers than yellow flowers.
So in Mark''s garden, there are 10 + 8 = <<10+8=18>>18 purple flowers.
Purple and yellow flowers sum up to 10 + 18 = <<10+18=28>>28 flowers.
That means in Mark''s garden there are 25/100 * 28 = <<25/100*28=7>>7 green flowers.
So in total Mark has 28 + 7 = <<28+7=35>>35 plants in his garden.
#### 35', '{"value":35}', 'other', 'flowers', '[{"name":"yellow flowers","value":10},{"name":"purple increase percent","value":80},{"name":"green proportion percent","value":25}]', 1, 3, 1, 2, 2, 5, '{"steps":[{"expr":"80/100*10","result":8},{"expr":"10+8","result":18},{"expr":"10+18","result":28},{"expr":"25/100*28","result":7},{"expr":"28+7","result":35}],"topic":"other","answer":"There are 80/100 * 10 = <<80/100*10=8>>8 more purple flowers than yellow flowers.\nSo in Mark''s garden, there are 10 + 8 = <<10+8=18>>18 purple flowers.\nPurple and yellow flowers sum up to 10 + 18 = <<10+18=28>>28 flowers.\nThat means in Mark''s garden there are 25/100 * 28 = <<25/100*28=7>>7 green flowers.\nSo in total Mark has 28 + 7 = <<28+7=35>>35 plants in his garden.\n#### 35","question":"Mark has a garden with flowers. He planted plants of three different colors in it. Ten of them are yellow, and there are 80% more of those in purple. There are only 25% as many green flowers as there are yellow and purple flowers. How many flowers does Mark have in his garden?","final_result":35,"number_range":"1-100","primary_unit":"flowers","number_of_steps":7,"operations_used":["division","multiplication","addition"],"cognitive_demand":"choose","unknown_position":"result_unknown","extracted_variables":[{"name":"yellow flowers","value":10},{"name":"purple increase percent","value":80},{"name":"green proportion percent","value":25}],"language_complexity":"relationship"}'),
  ('gsm8k', '6', NULL, 'Albert is wondering how much pizza he can eat in one day. He buys 2 large pizzas and 2 small pizzas. A large pizza has 16 slices and a small pizza has 8 slices. If he eats it all, how many pieces does he eat that day?', 'He eats 32 from the largest pizzas because 2 x 16 = <<2*16=32>>32
He eats 16 from the small pizza because 2 x 8 = <<2*8=16>>16
He eats 48 pieces because 32 + 16 = <<32+16=48>>48
#### 48', '{"value":48}', 'other', 'pieces', '[{"name":"large pizzas","value":2},{"name":"small pizzas","value":2},{"name":"slices per large pizza","value":16},{"name":"slices per small pizza","value":8}]', 1, 3, 1, 2, 2, 3, '{"steps":[{"expr":"2*16","result":32},{"expr":"2*8","result":16},{"expr":"32+16","result":48}],"topic":"other","answer":"He eats 32 from the largest pizzas because 2 x 16 = <<2*16=32>>32\nHe eats 16 from the small pizza because 2 x 8 = <<2*8=16>>16\nHe eats 48 pieces because 32 + 16 = <<32+16=48>>48\n#### 48","question":"Albert is wondering how much pizza he can eat in one day. He buys 2 large pizzas and 2 small pizzas. A large pizza has 16 slices and a small pizza has 8 slices. If he eats it all, how many pieces does he eat that day?","final_result":48,"number_range":"1-100","primary_unit":"pieces","number_of_steps":3,"operations_used":["multiplication","addition"],"cognitive_demand":"choose","unknown_position":"result_unknown","extracted_variables":[{"name":"large pizzas","value":2},{"name":"small pizzas","value":2},{"name":"slices per large pizza","value":16},{"name":"slices per small pizza","value":8}],"language_complexity":"relationship"}'),
  ('gsm8k', '7', NULL, 'Ken created a care package to send to his brother, who was away at boarding school.  Ken placed a box on a scale, and then he poured into the box enough jelly beans to bring the weight to 2 pounds.  Then, he added enough brownies to cause the weight to triple.  Next, he added another 2 pounds of jelly beans.  And finally, he added enough gummy worms to double the weight once again.  What was the final weight of the box of goodies, in pounds?', 'To the initial 2 pounds of jelly beans, he added enough brownies to cause the weight to triple, bringing the weight to 2*3=<<2*3=6>>6 pounds.
Next, he added another 2 pounds of jelly beans, bringing the weight to 6+2=<<6+2=8>>8 pounds.
And finally, he added enough gummy worms to double the weight once again, to a final weight of 8*2=<<8*2=16>>16 pounds.
#### 16', '{"value":16}', 'weights', 'pounds', '[{"name":"initial weight pounds","value":2},{"name":"triple factor","value":3},{"name":"additional jelly beans pounds","value":2},{"name":"double factor","value":2}]', 1, 3, 1, 2, 1, 3, '{"steps":[{"expr":"2*3","result":6},{"expr":"6+2","result":8},{"expr":"8*2","result":16}],"topic":"weights","answer":"To the initial 2 pounds of jelly beans, he added enough brownies to cause the weight to triple, bringing the weight to 2*3=<<2*3=6>>6 pounds.\nNext, he added another 2 pounds of jelly beans, bringing the weight to 6+2=<<6+2=8>>8 pounds.\nAnd finally, he added enough gummy worms to double the weight once again, to a final weight of 8*2=<<8*2=16>>16 pounds.\n#### 16","question":"Ken created a care package to send to his brother, who was away at boarding school.  Ken placed a box on a scale, and then he poured into the box enough jelly beans to bring the weight to 2 pounds.  Then, he added enough brownies to cause the weight to triple.  Next, he added another 2 pounds of jelly beans.  And finally, he added enough gummy worms to double the weight once again.  What was the final weight of the box of goodies, in pounds?","final_result":16,"number_range":"1-100","primary_unit":"pounds","number_of_steps":3,"operations_used":["multiplication","addition"],"cognitive_demand":"recall","unknown_position":"result_unknown","extracted_variables":[{"name":"initial weight pounds","value":2},{"name":"triple factor","value":3},{"name":"additional jelly beans pounds","value":2},{"name":"double factor","value":2}],"language_complexity":"relationship"}'),
  ('gsm8k', '8', NULL, 'Alexis is applying for a new job and bought a new set of business clothes to wear to the interview. She went to a department store with a budget of $200 and spent $30 on a button-up shirt, $46 on suit pants, $38 on a suit coat, $11 on socks, and $18 on a belt. She also purchased a pair of shoes, but lost the receipt for them. She has $16 left from her budget. How much did Alexis pay for the shoes?', 'Let S be the amount Alexis paid for the shoes.
She spent S + 30 + 46 + 38 + 11 + 18 = S + <<+30+46+38+11+18=143>>143.
She used all but $16 of her budget, so S + 143 = 200 - 16 = 184.
Thus, Alexis paid S = 184 - 143 = $<<184-143=41>>41 for the shoes.
#### 41', '{"value":41}', 'money', 'dollar', '[{"name":"budget dollars","value":200},{"name":"shirt cost","value":30},{"name":"pants cost","value":46},{"name":"coat cost","value":38},{"name":"socks cost","value":11},{"name":"belt cost","value":18},{"name":"remaining dollars","value":16}]', 2, 1, 2, 2, 2, 5, '{"steps":[{"expr":"+30+46+38+11+18","result":143},{"expr":"184-143","result":41}],"topic":"money","answer":"Let S be the amount Alexis paid for the shoes.\nShe spent S + 30 + 46 + 38 + 11 + 18 = S + <<+30+46+38+11+18=143>>143.\nShe used all but $16 of her budget, so S + 143 = 200 - 16 = 184.\nThus, Alexis paid S = 184 - 143 = $<<184-143=41>>41 for the shoes.\n#### 41","question":"Alexis is applying for a new job and bought a new set of business clothes to wear to the interview. She went to a department store with a budget of $200 and spent $30 on a button-up shirt, $46 on suit pants, $38 on a suit coat, $11 on socks, and $18 on a belt. She also purchased a pair of shoes, but lost the receipt for them. She has $16 left from her budget. How much did Alexis pay for the shoes?","final_result":41,"number_range":"100-500","primary_unit":"dollar","number_of_steps":6,"operations_used":["addition","subtraction"],"cognitive_demand":"choose","unknown_position":"change_unknown","extracted_variables":[{"name":"budget dollars","value":200},{"name":"shirt cost","value":30},{"name":"pants cost","value":46},{"name":"coat cost","value":38},{"name":"socks cost","value":11},{"name":"belt cost","value":18},{"name":"remaining dollars","value":16}],"language_complexity":"relationship"}'),
  ('gsm8k', '9', NULL, 'Tina makes $18.00 an hour.  If she works more than 8 hours per shift, she is eligible for overtime, which is paid by your hourly wage + 1/2 your hourly wage.  If she works 10 hours every day for 5 days, how much money does she make?', 'She works 8 hours a day for $18 per hour so she makes 8*18 = $<<8*18=144.00>>144.00 per 8-hour shift
She works 10 hours a day and anything over 8 hours is eligible for overtime, so she gets 10-8 = <<10-8=2>>2 hours of overtime
Overtime is calculated as time and a half so and she makes $18/hour so her overtime pay is 18*.5 = $<<18*.5=9.00>>9.00
Her overtime pay is 18+9 = $<<18+9=27.00>>27.00
Her base pay is $144.00 per 8-hour shift and she works 5 days and makes 5 * $144 = $<<144*5=720.00>>720.00
Her overtime pay is $27.00 per hour and she works 2 hours of overtime per day and makes 27*2 = $<<27*2=54.00>>54.00 in overtime pay
2 hours of overtime pay for 5 days means she makes 54*5 = $270.00
In 5 days her base pay is $720.00 and she makes $270.00 in overtime pay so she makes $720 + $270 = $<<720+270=990.00>>990.00
#### 990', '{"value":990}', 'money', 'dollar', '[{"name":"hourly wage dollars","value":18},{"name":"regular hour limit","value":8},{"name":"total hours per day","value":10},{"name":"days worked","value":5},{"name":"overtime extra fraction","value":0.5}]', 3, 3, 1, 2, 2, 5, '{"steps":[{"expr":"8*18","result":144},{"expr":"10-8","result":2},{"expr":"18*.5","result":9},{"expr":"18+9","result":27},{"expr":"144*5","result":720},{"expr":"27*2","result":54},{"expr":"720+270","result":990}],"topic":"money","answer":"She works 8 hours a day for $18 per hour so she makes 8*18 = $<<8*18=144.00>>144.00 per 8-hour shift\nShe works 10 hours a day and anything over 8 hours is eligible for overtime, so she gets 10-8 = <<10-8=2>>2 hours of overtime\nOvertime is calculated as time and a half so and she makes $18/hour so her overtime pay is 18*.5 = $<<18*.5=9.00>>9.00\nHer overtime pay is 18+9 = $<<18+9=27.00>>27.00\nHer base pay is $144.00 per 8-hour shift and she works 5 days and makes 5 * $144 = $<<144*5=720.00>>720.00\nHer overtime pay is $27.00 per hour and she works 2 hours of overtime per day and makes 27*2 = $<<27*2=54.00>>54.00 in overtime pay\n2 hours of overtime pay for 5 days means she makes 54*5 = $270.00\nIn 5 days her base pay is $720.00 and she makes $270.00 in overtime pay so she makes $720 + $270 = $<<720+270=990.00>>990.00\n#### 990","question":"Tina makes $18.00 an hour.  If she works more than 8 hours per shift, she is eligible for overtime, which is paid by your hourly wage + 1/2 your hourly wage.  If she works 10 hours every day for 5 days, how much money does she make?","final_result":990,"number_range":"500-1000","primary_unit":"dollar","number_of_steps":7,"operations_used":["multiplication","subtraction","addition"],"cognitive_demand":"choose","unknown_position":"result_unknown","extracted_variables":[{"name":"hourly wage dollars","value":18},{"name":"regular hour limit","value":8},{"name":"total hours per day","value":10},{"name":"days worked","value":5},{"name":"overtime extra fraction","value":0.5}],"language_complexity":"relationship"}')
ON CONFLICT (source, external_id) DO NOTHING;

-- Many-to-Many Relationships: seed_problem_operations
INSERT INTO seed_problem_operations (seed_problem_id, operation_id)
VALUES
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '0'), 4),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '0'), 1),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '1'), 4),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '1'), 3),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '2'), 4),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '2'), 3),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '2'), 2),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '3'), 3),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '3'), 1),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '3'), 2),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '3'), 4),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '4'), 3),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '5'), 4),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '5'), 3),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '5'), 1),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '6'), 3),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '6'), 1),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '7'), 3),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '7'), 1),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '8'), 1),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '8'), 2),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '9'), 3),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '9'), 2),
  ((SELECT id FROM seed_problems WHERE source = 'gsm8k' AND external_id = '9'), 1)
ON CONFLICT (seed_problem_id, operation_id) DO NOTHING;
