CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE operations (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE themes (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE objects (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT 
);

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  grade TEXT NOT NULL CHECK (grade IN ('3', '4')),

  -- Optional: only required for self-registered users
  email TEXT UNIQUE,

  auth_type TEXT NOT NULL CHECK (auth_type IN ('password', 'qr', 'anonymous')),
  username TEXT UNIQUE,
  password_hash TEXT,
  qr_token UUID UNIQUE DEFAULT uuid_generate_v4(),
  qr_generated_at TIMESTAMPTZ,

  -- Tracks who created the account
  created_by TEXT NOT NULL DEFAULT 'self' CHECK (created_by IN ('self', 'teacher')),
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Self-registered users must have email + password
  -- Teacher-created users must have a QR token (already defaulted)
  CONSTRAINT self_registered_requires_email
    CHECK (created_by != 'self' OR (email IS NOT NULL AND password_hash IS NOT NULL)),

  CONSTRAINT password_auth_requires_hash
    CHECK (auth_type != 'password' OR password_hash IS NOT NULL)
);

CREATE TABLE problems (
  id SERIAL PRIMARY KEY,
  operation_id INT REFERENCES operations(id),
  theme_id INT REFERENCES themes(id),
  problem_number INT NOT NULL,
  question_text TEXT NOT NULL,

  -- Object being asked about
  subject_object TEXT NOT NULL,          -- e.g. "legos", "apples", "students"

  -- Visual context
  emojis TEXT[] NOT NULL DEFAULT '{}',   -- e.g. ARRAY['🧱','🟥','🟦']
  colors TEXT[] DEFAULT '{}',            -- e.g. ARRAY['red','blue'] — empty if not relevant

  -- Answers (one or multiple correct)
  correct_answers TEXT[] NOT NULL,       -- e.g. ARRAY['150'] or ARRAY['red','blue']

  -- Hints generated by AI
  tips TEXT[] NOT NULL DEFAULT '{}',     -- e.g. ARRAY['Try dividing by 2 first', '...']

  difficulty INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE attempts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id),
  problem_id INT REFERENCES problems(id),
  answer_given TEXT,
  is_correct BOOLEAN,
  time_spent_seconds INT,
  score INT,
  attempted_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE sessions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  ended_at TIMESTAMPTZ
);